# Generated by Django 5.1.4 on 2024-12-28 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primary',
            new_name='PrimaryProfile',
        ),
        migrations.RenameModel(
            old_name='Secondary',
            new_name='SecondaryProfile',
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['user__username'], 'verbose_name': 'Photo'},
        ),
        migrations.AlterModelOptions(
            name='secondaryprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Secondary Profile', 'verbose_name_plural': 'Secondary Profiles!'},
        ),
    ]
