# Generated by Django 5.1.4 on 2024-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_primary_primaryprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreference',
            name='is_living_in_foreign',
            field=models.BooleanField(default=False, verbose_name='Living in a Foreign Country'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='is_planning_foreign',
            field=models.BooleanField(default=False, verbose_name='Planning to Move Abroad'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='living_foreign_country',
            field=models.CharField(blank=True, default=None, help_text='Leave blank if not seeking  foreign living partner', max_length=100, null=True, verbose_name='Country Living In'),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='planned_foreign_country',
            field=models.CharField(blank=True, default=None, help_text='Leave blank if if not seeking patner who is moving abroad', max_length=100, null=True, verbose_name='Planned Country to Move'),
        ),
    ]
