# Generated by Django 5.1.4 on 2024-12-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lifestyle_social_media_habits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreference',
            name='social_media_habits',
            field=models.CharField(choices=[('usual', 'Usual'), ('addicted', 'Addicted'), ('avoidant', 'Avoidant'), ('none', 'None')], default='usual', help_text='Describe your social media usage habits.', max_length=20, verbose_name='Social Media Habits'),
        ),
    ]
