# Generated by Django 5.1.4 on 2024-12-28 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_partnerpreference_social_media_habits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreference',
            name='monthly_income',
            field=models.IntegerField(blank=True, help_text='Enter your monthly income in integer format.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='occupation',
            field=models.CharField(blank=True, help_text='Enter your occupation.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='occupation_sector',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('business', 'Business'), ('other', 'Other')], max_length=20, null=True, verbose_name='Occupation Sector'),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
