# Generated by Django 5.1.4 on 2024-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_partnerpreference_monthly_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpreference',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='monthly_income_range',
            field=models.CharField(blank=True, help_text='E.g., 50,000-1,00,000', max_length=20, null=True, verbose_name='Preferred Monthly Income Range'),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='occupation',
            field=models.CharField(default='Any', help_text='what occupation should your pather have?', max_length=30),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='occupation_sector',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20, verbose_name='Occupation Sector Preference'),
        ),
    ]
