# Generated by Django 5.1.4 on 2024-12-29 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_partnerpreference_monthly_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryprofile',
            name='occupation_sector',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('business', 'Business'), ('other', 'Other'), ('None', 'None')], max_length=20, verbose_name='Occupation Sector'),
        ),
        migrations.AlterField(
            model_name='secondaryprofile',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10, verbose_name='Marital Status'),
        ),
        migrations.CreateModel(
            name='PartnerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(help_text='E.g., 25-35', max_length=6, verbose_name='Preferred Age Range')),
                ('height_range', models.CharField(help_text='E.g., 5\'2"-6\'0"', max_length=20, verbose_name='Preferred Height Range')),
                ('occupation', models.CharField(default='Any', help_text='what occupation should your pather have?', max_length=30)),
                ('occupation_sector', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('business', 'Business'), ('other', 'Other'), ('None', 'None')], default='other', max_length=20, verbose_name='Occupation Sector Preference')),
                ('monthly_income_range', models.CharField(blank=True, help_text='E.g., 50,000-1,00,000', max_length=20, null=True, verbose_name='Preferred Monthly Income Range')),
                ('nationality_preference', models.CharField(default='Nepali', max_length=100, verbose_name='Preferred Nationality')),
                ('religion_preference', models.CharField(default='Any', max_length=100, verbose_name='Preferred Religion')),
                ('caste_preference', models.CharField(default='Any', max_length=100, verbose_name='Preferred Caste')),
                ('smoking_preference', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], max_length=20, verbose_name='Smoking Habits Preference')),
                ('drinking_preference', models.CharField(choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly')], max_length=20, verbose_name='Drinking Habits Preference')),
                ('dietary_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=20, verbose_name='Dietary Preference')),
                ('fitness_level_preference', models.CharField(choices=[('not_active', 'Not Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], max_length=20, verbose_name='Fitness Level Preference')),
                ('interests_overlap', models.BooleanField(default=False, verbose_name='Similar Interests Required?')),
                ('location_preference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Patner Location')),
                ('is_planning_foreign', models.BooleanField(default=False, verbose_name='Planning to Move Abroad')),
                ('planned_foreign_country', models.CharField(blank=True, default=None, help_text='Leave blank if if not seeking patner who is moving abroad', max_length=100, null=True, verbose_name='Planned Country to Move')),
                ('is_living_in_foreign', models.BooleanField(default=False, verbose_name='Living in a Foreign Country')),
                ('living_foreign_country', models.CharField(blank=True, default=None, help_text='Leave blank if not seeking  foreign living partner', max_length=100, null=True, verbose_name='Country Living In')),
                ('social_media_habits', models.CharField(choices=[('usual', 'Usual'), ('addicted', 'Addicted'), ('avoidant', 'Avoidant'), ('none', 'None')], default='usual', help_text='Describe your social media usage habits.', max_length=20, verbose_name='Social Media Habits')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PartnerPreference',
        ),
    ]
